services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - DB_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db_migrate:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgres://postgres:password@db:5432/blogist?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  
volumes:
  caddy_data:
  caddy_config:
